enum PhotoSource {
  camera, 
  gallery,
}

enum DocKeyPhotoMemo {
  title, 
  memo, 
  createdBy, 
  photoFilename, 
  photoURL, 
  timestamp, 
  sharedWith,
}

class PhotoMemo {
  String? docId; //doc id generated by FireStore
  String createdBy; //email of the user
  String title;
  String memo;
  String photoFilename; //image/photo to store Storage
  String photoURL; //URL of the image
  DateTime? timestamp;
  late List<dynamic> sharedWith;

  PhotoMemo({
    this.docId,
    required this.createdBy,
    required this.title,
    required this.memo,
    required this.photoFilename,
    required this.photoURL,
    this.timestamp,
    List<dynamic>? sharedWith,
  }) {
    this.sharedWith = sharedWith == null ? [] : [...sharedWith];
  }





  Map<String, dynamic> toFirestoreDoc() {
    return {
     DocKeyPhotoMemo.title.name: title,
     DocKeyPhotoMemo.createdBy.name: createdBy,
     DocKeyPhotoMemo.memo.name: memo,
     DocKeyPhotoMemo.photoFilename.name: photoFilename,
     DocKeyPhotoMemo.photoURL.name: photoURL,
     DocKeyPhotoMemo.timestamp.name: timestamp,
     DocKeyPhotoMemo.sharedWith.name: sharedWith,
    };
  }
  
}