// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEBdXcTzGLUT5w-QHRepLKIriXmFjgOJc',
    appId: '1:556747256813:web:02d6fdd4bd2e5c00f0ade4',
    messagingSenderId: '556747256813',
    projectId: 'photo-memo-7ffdd',
    authDomain: 'photo-memo-7ffdd.firebaseapp.com',
    storageBucket: 'photo-memo-7ffdd.firebasestorage.app',
    measurementId: 'G-XJ0TE08WJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN4Diez_NNSfnwTGAs913f9iPO27onr2Y',
    appId: '1:556747256813:android:f2138fed3bc3e235f0ade4',
    messagingSenderId: '556747256813',
    projectId: 'photo-memo-7ffdd',
    storageBucket: 'photo-memo-7ffdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM0pjHj6J2ap1WVOB1K2lR4_sgwjWrLLU',
    appId: '1:556747256813:ios:3b105e1f4c03233cf0ade4',
    messagingSenderId: '556747256813',
    projectId: 'photo-memo-7ffdd',
    storageBucket: 'photo-memo-7ffdd.firebasestorage.app',
    iosBundleId: 'com.example.photoMemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM0pjHj6J2ap1WVOB1K2lR4_sgwjWrLLU',
    appId: '1:556747256813:ios:3b105e1f4c03233cf0ade4',
    messagingSenderId: '556747256813',
    projectId: 'photo-memo-7ffdd',
    storageBucket: 'photo-memo-7ffdd.firebasestorage.app',
    iosBundleId: 'com.example.photoMemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEBdXcTzGLUT5w-QHRepLKIriXmFjgOJc',
    appId: '1:556747256813:web:d12c4d5a865eae81f0ade4',
    messagingSenderId: '556747256813',
    projectId: 'photo-memo-7ffdd',
    authDomain: 'photo-memo-7ffdd.firebaseapp.com',
    storageBucket: 'photo-memo-7ffdd.firebasestorage.app',
    measurementId: 'G-KT83CKS1YW',
  );

}