// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtmMTfe1pstuUo9ZN1H3DFinEebWk9qlA',
    appId: '1:372685531168:web:25526969f045dbd15bb445',
    messagingSenderId: '372685531168',
    projectId: 'photo-memo-f4c32',
    authDomain: 'photo-memo-f4c32.firebaseapp.com',
    storageBucket: 'photo-memo-f4c32.appspot.com',
    measurementId: 'G-ML4DGPVNQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-5V_WpK-cjLnj9KEWo9Wba0UjpksXxnM',
    appId: '1:372685531168:android:10d678c275103f325bb445',
    messagingSenderId: '372685531168',
    projectId: 'photo-memo-f4c32',
    storageBucket: 'photo-memo-f4c32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLasR8cS5PX_e8cqyTMScJ2VDBV2Ro_mc',
    appId: '1:372685531168:ios:964106cb8d5ab3285bb445',
    messagingSenderId: '372685531168',
    projectId: 'photo-memo-f4c32',
    storageBucket: 'photo-memo-f4c32.appspot.com',
    iosBundleId: 'com.example.photoMemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLasR8cS5PX_e8cqyTMScJ2VDBV2Ro_mc',
    appId: '1:372685531168:ios:964106cb8d5ab3285bb445',
    messagingSenderId: '372685531168',
    projectId: 'photo-memo-f4c32',
    storageBucket: 'photo-memo-f4c32.appspot.com',
    iosBundleId: 'com.example.photoMemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtmMTfe1pstuUo9ZN1H3DFinEebWk9qlA',
    appId: '1:372685531168:web:93acccd3003d1cd65bb445',
    messagingSenderId: '372685531168',
    projectId: 'photo-memo-f4c32',
    authDomain: 'photo-memo-f4c32.firebaseapp.com',
    storageBucket: 'photo-memo-f4c32.appspot.com',
    measurementId: 'G-4NWHEGX177',
  );
}
